//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDK.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.ClassFeeDetails = new HashSet<ClassFeeDetail>();
            this.FeeSettings = new HashSet<FeeSetting>();
            this.Registrations = new HashSet<Registration>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string sessionName { get; set; }
        public Nullable<int> MaxPractical { get; set; }
        public Nullable<int> MiniPractical { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CoursesID { get; set; }
    
        public virtual ICollection<ClassFeeDetail> ClassFeeDetails { get; set; }
        public virtual ICollection<FeeSetting> FeeSettings { get; set; }
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
