//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDK.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeDBEntities : DbContext
    {
        public CollegeDBEntities()
            : base("name=CollegeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAST> CASTs { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<ClassFeeDetail> ClassFeeDetails { get; set; }
        public DbSet<CoursesType> CoursesTypes { get; set; }
        public DbSet<ExtraCertificate> ExtraCertificates { get; set; }
        public DbSet<FeeGroup> FeeGroups { get; set; }
        public DbSet<FeeHead> FeeHeads { get; set; }
        public DbSet<FeeSetting> FeeSettings { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
