//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDK.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesType
    {

        public int ID { get; set; }
        public string CoursesName { get; set; }
        public Nullable<decimal> C10PerCount { get; set; }
        public Nullable<decimal> C12PerCount { get; set; }
        public Nullable<decimal> GraducationPerCount { get; set; }
        public Nullable<decimal> ExtraMaxPer { get; set; }
        public string Sessionname { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
