//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDK.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraCertificate
    {
        public ExtraCertificate()
        {
            this.Registrations = new HashSet<Registration>();
            this.Registrations1 = new HashSet<Registration>();
            this.Registrations2 = new HashSet<Registration>();
            this.Registrations3 = new HashSet<Registration>();
            this.Registrations4 = new HashSet<Registration>();
        }
    
        public int CertificateId { get; set; }
        public string CertificateName { get; set; }
        public Nullable<decimal> CertificatePersent { get; set; }
        public string SessionName { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
        public virtual ICollection<Registration> Registrations1 { get; set; }
        public virtual ICollection<Registration> Registrations2 { get; set; }
        public virtual ICollection<Registration> Registrations3 { get; set; }
        public virtual ICollection<Registration> Registrations4 { get; set; }
    }
}
