//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemoRestorent.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeHead
    {
        public FeeHead()
        {
            this.ClassFeeDetails = new HashSet<ClassFeeDetail>();
            this.FeeSettings = new HashSet<FeeSetting>();
            this.FeeSettings1 = new HashSet<FeeSetting>();
        }
    
        public int FeeId { get; set; }
        public int FeeGroupId { get; set; }
        public string SessionName { get; set; }
        public string FeeeName { get; set; }
        public string FeeSection { get; set; }
        public string FeeType { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<ClassFeeDetail> ClassFeeDetails { get; set; }
        public virtual FeeGroup FeeGroup { get; set; }
        public virtual ICollection<FeeSetting> FeeSettings { get; set; }
        public virtual ICollection<FeeSetting> FeeSettings1 { get; set; }
    }
}
