//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDK.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeSetting
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int FromFeeHeadId { get; set; }
        public int ToFeeHeadId { get; set; }
        public string Operation { get; set; }
        public Nullable<int> Amount { get; set; }
        public string MaxLimit { get; set; }
        public string SessionName { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual FeeHead FeeHead { get; set; }
        public virtual FeeHead FeeHead1 { get; set; }
        public virtual Session Session { get; set; }
    }
}
