//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDemoRestorent.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string RegistrationNo { get; set; }
        public string FormNo { get; set; }
        public int RecNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public int ClassId { get; set; }
        public int CastId { get; set; }
        public string STitle { get; set; }
        public string StudentFName { get; set; }
        public string StudentLName { get; set; }
        public string FTitle { get; set; }
        public Nullable<decimal> RegFee { get; set; }
        public Nullable<decimal> C10MaxMarks { get; set; }
        public Nullable<decimal> C12MaxMarks { get; set; }
        public Nullable<decimal> GraducateMaxMarks { get; set; }
        public Nullable<decimal> C10ObtenMarks { get; set; }
        public Nullable<decimal> C12ObtenMarks { get; set; }
        public Nullable<decimal> GraducateObtenMarks { get; set; }
        public Nullable<decimal> C10Per { get; set; }
        public Nullable<decimal> C12Per { get; set; }
        public Nullable<decimal> GraducatePer { get; set; }
        public int ExtraId1 { get; set; }
        public Nullable<decimal> ExtraPer1 { get; set; }
        public int ExtraId2 { get; set; }
        public Nullable<decimal> ExtraPer2 { get; set; }
        public int ExtraId3 { get; set; }
        public Nullable<decimal> ExtraPer3 { get; set; }
        public int ExtraId4 { get; set; }
        public Nullable<decimal> ExtraPer4 { get; set; }
        public int ExtraId5 { get; set; }
        public Nullable<decimal> ExtraPer5 { get; set; }
        public Nullable<decimal> TotalExtraPer { get; set; }
        public Nullable<decimal> TotalEducationPer { get; set; }
        public string Remark { get; set; }
        public string SessionName { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CAST CAST { get; set; }
        public virtual Class Class { get; set; }
        public virtual ExtraCertificate ExtraCertificate { get; set; }
        public virtual ExtraCertificate ExtraCertificate1 { get; set; }
        public virtual ExtraCertificate ExtraCertificate2 { get; set; }
        public virtual ExtraCertificate ExtraCertificate3 { get; set; }
        public virtual ExtraCertificate ExtraCertificate4 { get; set; }
    }
}
